branch-defaults:
  master:
    environment: aws-beanstalk-test-dev
global:
  application_name: aws-beanstalk-test
  default_ec2_keyname: null
  default_platform: Ruby 2.2 (Puma)
  default_region: us-west-2
  profile: eb-cli
  sc: git
